In [6]:
d1={1,2,2,3,3,4,4}#no error but output wont have copies
d1

{1, 2, 3, 4}

In [1]:
import numpy as np#as gives alias name
a1=np.array([1,2,3])#one dimensional array
a1.dtype

dtype('int64')

In [2]:
a2=np.array([1,2,3,4],dtype='int16')
print(a2.dtype)

int16


In [4]:
import sys#system library to get size of integer 
sys.getsizeof(3)

28

In [7]:
print("array length:",a2.size)

array length: 4


In [10]:
print("array size:",a2.itemsize*a2.size)

array size: 8


In [11]:
a1=np.array([1,2,3,4])
a2=np.array([(1,2,3),(11,21,31)])
a22=np.array([[11,12,13],[15,17,19]])
print(a1)
print(a2)
print(a22)

[1 2 3 4]
[[ 1  2  3]
 [11 21 31]]
[[11 12 13]
 [15 17 19]]


In [14]:
a3=np.array([[(1,2,3,4),(11,12,13,14)],[(5,6,7,8),(15,16,17,18)]])
print(a3)

[[[ 1  2  3  4]
  [11 12 13 14]]

 [[ 5  6  7  8]
  [15 16 17 18]]]


In [15]:
print(a1.size)
print(a1.shape)
print(a1.ndim)
print("===a1===")
print(a2.size)
print(a2.shape)
print(a2.ndim)
print("===a2===")
print(a3.size)
print(a3.shape)
print(a3.ndim)
print("===a3===")

4
(4,)
1
===a1===
6
(2, 3)
2
===a2===
16
(2, 2, 4)
3
===a3===


In [17]:
#create special array-zeroes,ones and identity
a4=np.ones((2,3))
a4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a6=np.eye(3)
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
a7=np.identity(4)
a7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#full function
a8=np.full((2,4),7)
a8

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [23]:
a9=np.full(a2.shape,5)
a9

array([[5, 5, 5],
       [5, 5, 5]])

In [21]:
a10=np.full_like(a1,9)
a10

array([9, 9, 9, 9])

In [24]:
#random array
np.random.randint(3,67)

57

In [27]:
#range of values
a11=np.arange(4)
a11

array([0, 1, 2, 3])

In [29]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
#slicing
print(a1)
print(a2)


[1 2 3 4]
[[ 1  2  3]
 [11 21 31]]


In [31]:
print(a1[1])

2


In [32]:
print(a2[1,0])


11


In [33]:
print(a2[:,0:1])

[[ 1]
 [11]]


In [46]:
#select one element from each row of an array using the index value given in another array
a=np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
b=np.array([0,1,2,1])#op[1,5,9,11]
#get the shape of array a in a tuple variable
t1=a.shape
print(t1[0])

4


In [47]:
#lab program 8:generator one hot encodings for an array in NumPy
#y=mx+c x=yrs of exp y=salary m and c with y and x values y=15000x+10000
#red,green,blue [r,g,b,r,b,b,g,g,r,r]=2D arraybinary value
#r=0,g=1,b=2
#[0,1,2,0,2,2,1,1,0,0]
#no of rows=no of values=10 or 4
#no of columns=max value+1{if starting from 1 else same value if starting from 0}
#for simplicity lets take values [0,1,2,0]
#[1 0 0 0
# 0 1 0 0
# 0 0 1 0
# 1 0 0 0]




SyntaxError: ignored

In [58]:
#8.generate one hot encodings for an array in NumPy.
#eg array [2,1,3,0]
a=np.array([2,1,3,0])
print(a.max())
print(a.min())
a1=np.zeros((a.size,a.max()+1))
print(a1)

3
0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
#get shape of an array a in tuple variables
t1=a.shape
print(t1[0])


4


In [37]:
np.arange(t1[0])

array([0, 1, 2, 3])

In [38]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
a[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a[0:3,[1,2]]


array([[2, 3],
       [5, 6],
       [8, 9]])

In [41]:
a[0:3,1]

array([2, 5, 8])

In [43]:
np.arange(t1[0])

array([0, 1, 2, 3])

In [44]:
a[np.arange(t1[0]),b]

array([ 1,  5,  9, 11])

In [45]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# empty dictionary
d2=dict()
d3={}
d2
d3

{}

In [ ]:
# create dictionary with key as usn and values as cgpa
d3= {'CS210019':7.9,'Cs210018': 7.5}
print(d3)
d4 = dict({'CS210019':8.9,'Cs210018': 7.3})
d4

{'CS210019': 7.9, 'Cs210018': 7.5}


{'CS210019': 8.9, 'Cs210018': 7.3}

In [ ]:
d5= dict([('CS210019',8.9),('Cs210018',7.3)])
d5

{'CS210019': 8.9, 'Cs210018': 7.3}

In [ ]:
print(len(d5))

2


In [ ]:
d5['CS210019']

8.9

In [ ]:
# retrieve all the key-value pairs
print(type(d5.items()))

<class 'dict_items'>


In [ ]:
# retrieve all the keys
print(type(d5.keys()))
print(d5.keys())
dkeys=d5.keys()
l1=list(dkeys)
l1[0]

<class 'dict_keys'>
dict_keys(['CS210019', 'Cs210018'])


'CS210019'

In [ ]:
d5.get('CS210029',0)

0

In [ ]:

print(d5)
d5.get('CS210019',0)

{'CS210019': 8.9, 'Cs210018': 7.3}


8.9

In [ ]:
# retrieve all the values
print(d5.values())

dict_values([8.9, 7.3])


In [ ]:
type(d5)

dict

In [ ]:
for key in d5:
    print(key, d5[key])

CS210019 8.9
Cs210018 7.3


In [ ]:
''' 1. Create a dictionary with usn as key and values is list of 
marks in 3 subjects
2. Display the usn with average marks
3. Display the usn and marks in sorted order of usn
4. Display the usn and average in sorted order of usn

In [ ]:
studict = {'cs014':[18,15,19], 'cs004':[18,12,14],'cs016':[8,18,19]}
studict

{'cs014': [18, 15, 19], 'cs004': [18, 12, 14], 'cs016': [8, 18, 19]}

In [ ]:
len(studict)

3

In [ ]:
l1=studict['cs014']
print(l1)
avg=sum(l1)/len(l1)
avg

[18, 15, 19]


17.333333333333332

In [ ]:
for usn in studict:
    l1=studict[usn]
    avg=sum(l1)/len(l1)
    print("for the {} with values:{} the average is {}".format(usn,l1, avg))

for the cs014 with values:[18, 15, 19] the average is 17.333333333333332
for the cs004 with values:[18, 12, 14] the average is 14.666666666666666
for the cs016 with values:[8, 18, 19] the average is 15.0
